In [1]:
import pandas as pd
import numpy as np

# Train

In [2]:
df_train = pd.read_csv('aes_train.csv', index_col=0)
df_train.head()

category  beauty_scores
1304908208.jpg   people              1
5864195780.jpg   nature              3
5406120849.jpg    urban              3
7454407976.jpg   people              3
5672480.jpg      nature              2

In [3]:
bins = np.bincount(df_train['beauty_scores'].values)
bins

array([  21,  498, 6492, 3881,  201])

In [4]:
bins[1:-1]

array([ 498, 6492, 3881])

In [5]:
lst = []
for idx, i in enumerate(bins[1:-1]):
    tmp = df_train[df_train['beauty_scores'] == idx+1]
    lst.append(tmp.iloc[:498, ])

In [6]:
df_train_new = pd.concat(lst)

In [7]:
df_train_new.head()

category  beauty_scores
1304908208.jpg   people              1
2831778165.jpg   nature              1
2622568994.jpg   nature              1
2347772663.jpg   people              1
6811194858.jpg    urban              1

In [8]:
df_train_new['beauty_scores'] = df_train_new['beauty_scores'] - 1

In [9]:
bins = np.bincount(df_train_new['beauty_scores'].values)
bins

array([498, 498, 498])

In [10]:
df_train_new.to_csv('aes_train_balanced.csv')

# Valid

In [11]:
df_valid = pd.read_csv('aes_valid.csv', index_col=0)
df_valid.head()

category  beauty_scores
7799253746.jpg   people              3
2909845322.jpg  animals              2
4525271413.jpg   nature              2
1015083599.jpg   nature              2
2258601857.jpg   nature              1

In [12]:
bins = np.bincount(df_valid['beauty_scores'].values)
bins

array([  5,  26, 412, 238,  12])

In [13]:
bins[1:-1]

array([ 26, 412, 238])

In [14]:
lst = []
for idx, i in enumerate(bins[1:-1]):
    tmp = df_valid[df_valid['beauty_scores'] == idx+1]
    lst.append(tmp.iloc[:26, ])

In [15]:
df_valid_new = pd.concat(lst)

In [16]:
df_valid_new.head()

category  beauty_scores
2258601857.jpg   nature              1
362231585.jpg    people              1
7173535357.jpg   people              1
6468741413.jpg   nature              1
2688220799.jpg   nature              1

In [17]:
df_valid_new['beauty_scores'] = df_valid_new['beauty_scores'] - 1

In [18]:
bins = np.bincount(df_valid_new['beauty_scores'].values)
bins

array([26, 26, 26])

In [19]:
df_valid_new.to_csv('morph2_valid_balanced.csv')

# Test

In [20]:
df_test = pd.read_csv('aes_test.csv', index_col=0)
df_test.head()

category  beauty_scores
3959594639.jpg   nature              2
4860910757.jpg  animals              3
2354250665.jpg   nature              3
4449582739.jpg   people              3
6354973971.jpg   people              3

In [21]:
bins = np.bincount(df_test['beauty_scores'].values)
bins

array([   6,   96, 1220,  725,   34])

In [22]:
bins[1:-1]

array([  96, 1220,  725])

In [23]:
lst = []
for idx, i in enumerate(bins[1:-1]):
    tmp = df_test[df_test['beauty_scores'] == idx+1]
    lst.append(tmp.iloc[:96, ])

In [24]:
df_test_new = pd.concat(lst)

In [25]:
df_test_new.head()

category  beauty_scores
4422940902.jpg  animals              1
171485923.jpg    nature              1
2350195671.jpg   nature              1
5861005710.jpg  animals              1
5960562059.jpg   nature              1

In [26]:
df_test_new['beauty_scores'] = df_test_new['beauty_scores'] - 1

In [27]:
bins = np.bincount(df_test_new['beauty_scores'].values)
bins

array([96, 96, 96])

In [28]:
df_test_new.to_csv('morph2_test_balanced.csv')