In [1]:
import pandas as pd
import numpy as np

# Train

In [2]:
df_train = pd.read_csv('morph2_train.csv', index_col=0)
df_train.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
321798_03M36.jpg  321798            3    B     1          NaN   20      NaN   
285760_00M18.jpg  285760            0    B     1          NaN    2      NaN   
315806_00M16.jpg  315806            0    B     1          NaN    0      NaN   
307105_00M33.jpg  307105            0    B     1          NaN   17      NaN   
067089_5M41.jpg    67089            5    B     1          NaN   25      NaN   

                 quality  
321798_03M36.jpg    GOOD  
285760_00M18.jpg    GOOD  
315806_00M16.jpg    GOOD  
307105_00M33.jpg    GOOD  
067089_5M41.jpg     GOOD

In [3]:
bins = np.bincount(df_train['age'].values)
bins

array([1083, 1328, 1480, 1524, 1390, 1256, 1351, 1313, 1286, 1225, 1138,
       1028,  960,  857,  835,  898,  913, 1114, 1218, 1399, 1330, 1191,
       1097, 1025, 1031, 1137, 1135, 1013,  901,  865,  744,  696,  625,
        535,  479,  443,  390,  364,  252,  232,  167,  126,   91,   66,
         54,   48,   23,   31,   29,   18,    8,    9,    3,    5,    5])

In [4]:
bins[:33]

array([1083, 1328, 1480, 1524, 1390, 1256, 1351, 1313, 1286, 1225, 1138,
       1028,  960,  857,  835,  898,  913, 1114, 1218, 1399, 1330, 1191,
       1097, 1025, 1031, 1137, 1135, 1013,  901,  865,  744,  696,  625])

In [5]:
lst = []
for idx, i in enumerate(bins[:33]):
    tmp = df_train[df_train['age'] == idx]
    lst.append(tmp.iloc[:625, ])

In [6]:
df_train_new = pd.concat(lst)

In [7]:
df_train_new.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
315806_00M16.jpg  315806            0    B     1          NaN    0      NaN   
334740_02M16.jpg  334740            2    B     1          NaN    0      NaN   
327774_02M16.jpg  327774            2    B     1          NaN    0      NaN   
326445_01M16.jpg  326445            1    W     1          NaN    0      NaN   
330379_02M16.jpg  330379            2    B     1          NaN    0      NaN   

                 quality  
315806_00M16.jpg    GOOD  
334740_02M16.jpg    GOOD  
327774_02M16.jpg    GOOD  
326445_01M16.jpg    GOOD  
330379_02M16.jpg    GOOD

In [8]:
bins = np.bincount(df_train_new['age'].values)
bins

array([625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625,
       625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625, 625,
       625, 625, 625, 625, 625, 625, 625])

In [9]:
df_train_new.to_csv('morph2_train_balanced.csv')

# Valid

In [10]:
df_valid = pd.read_csv('morph2_valid.csv', index_col=0)
df_valid.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
201620_00M29.jpg  201620            0    B     1          NaN   13      NaN   
290135_03M22.jpg  290135            3    B     1          NaN    6      NaN   
074598_2M37.jpg    74598            2    B     1          NaN   21      NaN   
074598_0M35.jpg    74598            0    B     1          NaN   19      NaN   
276393_03F28.jpg  276393            3    B    -1          NaN   12      NaN   

                 quality  
201620_00M29.jpg    GOOD  
290135_03M22.jpg    GOOD  
074598_2M37.jpg     GOOD  
074598_0M35.jpg     GOOD  
276393_03F28.jpg    GOOD

In [11]:
bins = np.bincount(df_valid['age'].values)
bins

array([118, 143, 155, 156, 175, 128, 161, 135, 143, 129, 127, 111, 122,
       105,  97, 117, 101, 137, 129, 143, 127, 128, 137, 124, 122, 136,
       123, 105,  96, 106,  89,  68,  55,  61,  40,  47,  52,  33,  35,
        22,  26,  15,   7,   8,   3,   5,   4,   1,   4,   1,   2,   0,
         1,   0,   1])

In [12]:
bins[:33]

array([118, 143, 155, 156, 175, 128, 161, 135, 143, 129, 127, 111, 122,
       105,  97, 117, 101, 137, 129, 143, 127, 128, 137, 124, 122, 136,
       123, 105,  96, 106,  89,  68,  55])

In [13]:
lst = []
for idx, i in enumerate(bins[:33]):
    tmp = df_valid[df_valid['age'] == idx]
    lst.append(tmp.iloc[:55, ])

In [14]:
df_valid_new = pd.concat(lst)

In [15]:
df_valid_new.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
341774_02M16.jpg  341774            2    B     1          NaN    0      NaN   
321579_00M16.jpg  321579            0    B     1          NaN    0      NaN   
340446_00M16.jpg  340446            0    B     1          NaN    0      NaN   
341265_02M16.jpg  341265            2    B     1          NaN    0      NaN   
338471_01M16.jpg  338471            1    W     1          NaN    0      NaN   

                 quality  
341774_02M16.jpg    GOOD  
321579_00M16.jpg    GOOD  
340446_00M16.jpg    GOOD  
341265_02M16.jpg    GOOD  
338471_01M16.jpg    GOOD

In [16]:
bins = np.bincount(df_valid_new['age'].values)
bins

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [17]:
df_valid_new.to_csv('morph2_valid_balanced.csv')

# Test

In [18]:
df_test = pd.read_csv('morph2_test.csv', index_col=0)
df_test.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
273546_01M22.jpg  273546            1    B     1          NaN    6      NaN   
306329_00F32.jpg  306329            0    B    -1          NaN   16      NaN   
124805_06F54.jpg  124805            6    B    -1          NaN   38      NaN   
066525_3M45.jpg    66525            3    B     1          NaN   29      NaN   
098195_6F46.jpg    98195            6    B    -1          NaN   30      NaN   

                 quality  
273546_01M22.jpg    GOOD  
306329_00F32.jpg    GOOD  
124805_06F54.jpg    GOOD  
066525_3M45.jpg     GOOD  
098195_6F46.jpg     GOOD

In [19]:
bins = np.bincount(df_test['age'].values)
bins

array([273, 384, 414, 410, 420, 371, 321, 369, 357, 351, 273, 270, 264,
       216, 224, 267, 273, 306, 353, 354, 376, 351, 289, 325, 281, 297,
       307, 291, 284, 243, 232, 194, 197, 148, 121, 130, 110,  81,  78,
        59,  41,  27,  21,  22,  15,  13,  15,   3,   3,   7,   5,   4,
         0,   3,   1])

In [20]:
bins[:33]

array([273, 384, 414, 410, 420, 371, 321, 369, 357, 351, 273, 270, 264,
       216, 224, 267, 273, 306, 353, 354, 376, 351, 289, 325, 281, 297,
       307, 291, 284, 243, 232, 194, 197])

In [21]:
lst = []
for idx, i in enumerate(bins[:33]):
    tmp = df_test[df_test['age'] == idx]
    lst.append(tmp.iloc[:190, ])

In [22]:
df_test_new = pd.concat(lst)

In [23]:
df_test_new.head()

id_num  picture_num race  Male  facial_hair  age  glasses  \
330519_01F16.jpg  330519            1    W    -1          NaN    0      NaN   
349676_02M16.jpg  349676            2    B     1          NaN    0      NaN   
335235_00M16.jpg  335235            0    B     1          NaN    0      NaN   
319410_01M16.jpg  319410            1    B     1          NaN    0      NaN   
329559_00M16.jpg  329559            0    H     1          NaN    0      NaN   

                 quality  
330519_01F16.jpg    GOOD  
349676_02M16.jpg    GOOD  
335235_00M16.jpg    GOOD  
319410_01M16.jpg    GOOD  
329559_00M16.jpg    GOOD

In [24]:
bins = np.bincount(df_test_new['age'].values)
bins

array([190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190,
       190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190,
       190, 190, 190, 190, 190, 190, 190])

In [25]:
df_test_new.to_csv('morph2_test_balanced.csv')