In [1]:
import pandas as pd
import numpy as np

# Train

In [2]:
df_train = pd.read_csv('afad_train.csv')
df_train.head()

file                 path  age  gender
0  131152-0.jpg  31/111/131152-0.jpg   16    male
1  192493-0.jpg  23/112/192493-0.jpg    8  female
2   43267-0.jpg   20/111/43267-0.jpg    5    male
3  482067-0.jpg  35/112/482067-0.jpg   20  female
4  447249-0.jpg  29/111/447249-0.jpg   14    male

In [3]:
bins = np.bincount(df_train['age'].values)
bins

array([  951,  1841,  1887,  4245,  9482, 10056,  9545, 10314,  7987,
        9797,  8558,  5834,  4926,  3929,  3595,  3653,  3387,  3037,
        2813,  2931,  3227,  3218,  2962,  2886,  2881,  1015])

In [4]:
bins[3:16]

array([ 4245,  9482, 10056,  9545, 10314,  7987,  9797,  8558,  5834,
        4926,  3929,  3595,  3653])

In [5]:
lst = []
for idx, i in enumerate(bins[3:16]):
    tmp = df_train[df_train['age'] == idx+3]
    lst.append(tmp.iloc[:3550, ])

In [6]:
df_train_new = pd.concat(lst)

In [7]:
df_train_new.head()

file                 path  age  gender
19   272796-0.jpg  18/112/272796-0.jpg    3  female
46   108631-0.jpg  18/111/108631-0.jpg    3    male
52    55704-0.jpg   18/111/55704-0.jpg    3    male
72   281968-0.jpg  18/112/281968-0.jpg    3  female
116  236736-0.jpg  18/111/236736-0.jpg    3    male

In [8]:
df_train_new['age'] = df_train_new['age'] - 3

In [9]:
bins = np.bincount(df_train_new['age'].values)
bins

array([3550, 3550, 3550, 3550, 3550, 3550, 3550, 3550, 3550, 3550, 3550,
       3550, 3550])

In [10]:
df_train_new.to_csv('afad_train_balanced.csv', index=None)

# Valid

In [11]:
df_valid = pd.read_csv('afad_valid.csv')
df_valid.head()

file                 path  age  gender
0  202476-0.jpg  25/111/202476-0.jpg   10    male
1  430719-0.jpg  32/111/430719-0.jpg   17    male
2  261204-0.jpg  22/111/261204-0.jpg    7    male
3  108660-0.jpg  20/112/108660-0.jpg    5  female
4   83797-0.jpg   22/111/83797-0.jpg    7    male

In [12]:
bins = np.bincount(df_valid['age'].values)
bins

array([ 50,  97,  99, 223, 499, 529, 503, 543, 421, 516, 451, 307, 259,
       207, 189, 192, 178, 160, 148, 154, 170, 169, 156, 152, 152,  53])

In [13]:
bins[3:16]

array([223, 499, 529, 503, 543, 421, 516, 451, 307, 259, 207, 189, 192])

In [14]:
lst = []
for idx, i in enumerate(bins[3:16]):
    tmp = df_valid[df_valid['age'] == idx+3]
    lst.append(tmp.iloc[:189, ])

In [15]:
df_valid_new = pd.concat(lst)

In [16]:
df_valid_new.head()

file                 path  age  gender
33   288701-0.jpg  18/111/288701-0.jpg    3    male
44   270216-0.jpg  18/111/270216-0.jpg    3    male
46    55026-1.jpg   18/111/55026-1.jpg    3    male
93    55644-0.jpg   18/112/55644-0.jpg    3  female
177   55417-1.jpg   18/111/55417-1.jpg    3    male

In [17]:
df_valid_new['age'] = df_valid_new['age'] - 3

In [18]:
bins = np.bincount(df_valid_new['age'].values)
bins

array([189, 189, 189, 189, 189, 189, 189, 189, 189, 189, 189, 189, 189])

In [19]:
df_valid_new.to_csv('afad_valid_balanced.csv', index=None)

# Test

In [20]:
df_test = pd.read_csv('afad_test.csv')
df_test.head()

file                 path  age  gender
0   87278-0.jpg   22/111/87278-0.jpg    7    male
1  308311-0.jpg  35/111/308311-0.jpg   20    male
2  100448-3.jpg  24/112/100448-3.jpg    9  female
3  442013-0.jpg  30/111/442013-0.jpg   15    male
4   43763-0.jpg   19/111/43763-0.jpg    4    male

In [21]:
bins = np.bincount(df_test['age'].values)
bins

array([ 250,  485,  496, 1117, 2496, 2647, 2512, 2715, 2102, 2578, 2252,
       1535, 1296, 1034,  946,  961,  891,  799,  740,  771,  849,  847,
        780,  760,  758,  267])

In [22]:
bins[3:16]

array([1117, 2496, 2647, 2512, 2715, 2102, 2578, 2252, 1535, 1296, 1034,
        946,  961])

In [23]:
lst = []
for idx, i in enumerate(bins[3:16]):
    tmp = df_test[df_test['age'] == idx+3]
    lst.append(tmp.iloc[:945, ])

In [24]:
df_test_new = pd.concat(lst)

In [25]:
df_test_new.head()

file                 path  age  gender
43   291326-0.jpg  18/112/291326-0.jpg    3  female
50   288165-0.jpg  18/111/288165-0.jpg    3    male
54   291375-0.jpg  18/111/291375-0.jpg    3    male
122  286601-0.jpg  18/112/286601-0.jpg    3  female
149  286742-0.jpg  18/111/286742-0.jpg    3    male

In [26]:
df_test_new['age'] = df_test_new['age'] - 3

In [27]:
bins = np.bincount(df_test_new['age'].values)
bins

array([945, 945, 945, 945, 945, 945, 945, 945, 945, 945, 945, 945, 945])

In [28]:
df_test_new.to_csv('afad_test_balanced.csv', index=None)