In [1]:
import pandas as pd
import numpy as np

# Train

In [2]:
df = pd.read_csv('../data/processed/california_housing/californiahousing.csv')
df.head()

response      V1     V2  V3    V4    V5    V6    V7      V8
0         6 -122.23  37.88  41   880   129   322   126  8.3252
1         5 -122.22  37.86  21  7099  1106  2401  1138  8.3014
2         5 -122.24  37.85  52  1467   190   496   177  7.2574
3         5 -122.25  37.85  52  1274   235   558   219  5.6431
4         5 -122.25  37.85  52  1627   280   565   259  3.8462

In [3]:
bins = np.bincount(df['response'].values)
bins

array([   0, 3244, 6845, 5074, 2549, 1379, 1549])

In [4]:
bins[1:]

array([3244, 6845, 5074, 2549, 1379, 1549])

In [5]:
lst = []
for idx, i in enumerate(bins[1:]):
    tmp = df[df['response'] == idx+1]
    lst.append(tmp.iloc[:1379, ])

In [6]:
df_new = pd.concat(lst)

In [7]:
df_new.head()

response      V1     V2  V3    V4   V5    V6   V7      V8
26         1 -122.28  37.85  49  1130  244   607  239  2.4597
51         1 -122.27  37.82  43  1868  456  1061  407  1.5045
54         1 -122.28  37.82  52  1170  235   701  233  1.6098
55         1 -122.28  37.82  52   945  243   576  220  1.4113
56         1 -122.28  37.82  52  1238  288   622  259  1.5057

In [8]:
df_new['response'] = df_new['response'] - 1

In [9]:
bins = np.bincount(df_new['response'].values)
bins

array([1379, 1379, 1379, 1379, 1379, 1379])

## Split

In [10]:
indices = np.arange(df_new.shape[0])
labels = df_new['response'].values

In [11]:
from sklearn.model_selection import train_test_split


indices_train, indices_test, labels_train, labels_test = train_test_split(
    indices, labels, test_size=0.2, random_state=123, shuffle=True, stratify=labels)

indices_train, indices_valid, labels_train, labels_valid = train_test_split(
    indices_train, labels_train, test_size=0.05, random_state=123, shuffle=True, stratify=labels_train)

In [12]:
df_train = df_new.iloc[indices_train]
df_train.to_csv('../data/processed/california_housing/californiahousing_balanced_train.csv', index=None)

df_valid = df_new.iloc[indices_valid]
df_valid.to_csv('../data/processed/california_housing/californiahousing_balanced_valid.csv', index=None)

df_test = df_new.iloc[indices_test]
df_test.to_csv('../data/processed/california_housing/californiahousing_balanced_test.csv', index=None)