In [1]:
import pandas as pd
import numpy as np

# Train

In [2]:
df = pd.read_csv('../data/processed/fireman_example/fireman_example.csv')
df.head()

response     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
0        12  0.487  0.072  0.004  0.833  0.765  0.600  0.132  0.886  0.073   
1         8  0.223  0.401  0.659  0.528  0.843  0.713  0.580  0.473  0.572   
2        15  0.903  0.913  0.940  0.979  0.561  0.744  0.627  0.818  0.309   
3        13  0.791  0.857  0.359  0.844  0.155  0.948  0.114  0.292  0.412   
4        16  0.326  0.593  0.085  0.927  0.926  0.633  0.431  0.326  0.031   

     V10  
0  0.342  
1  0.528  
2  0.510  
3  0.991  
4  0.730

In [3]:
bins = np.bincount(df['response'].values)
bins

array([   0, 2548, 2549, 2549, 2549, 2545, 2550, 2551, 2543, 2548, 2551,
       2546, 2547, 2550, 2546, 2551, 2545])

In [4]:
bins[1:]

array([2548, 2549, 2549, 2549, 2545, 2550, 2551, 2543, 2548, 2551, 2546,
       2547, 2550, 2546, 2551, 2545])

In [5]:
lst = []
for idx, i in enumerate(bins[1:]):
    tmp = df[df['response'] == idx+1]
    lst.append(tmp.iloc[:2543, ])

In [6]:
df_new = pd.concat(lst)

In [7]:
df_new.head()

response     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
26          1  0.059  0.134  0.387  0.225  0.139  0.547  0.792  0.853  0.138   
71          1  0.868  0.068  0.230  0.214  0.272  0.448  0.693  0.872  0.962   
93          1  0.638  0.045  0.374  0.150  0.653  0.356  0.477  0.445  0.007   
96          1  0.180  0.435  0.537  0.179  0.072  0.885  0.510  0.275  0.497   
114         1  0.005  0.213  0.792  0.149  0.925  0.561  0.275  0.620  0.162   

       V10  
26   0.383  
71   0.311  
93   0.441  
96   0.159  
114  0.386

In [8]:
df_new['response'] = df_new['response'] - 1

In [9]:
bins = np.bincount(df_new['response'].values)
bins

array([2543, 2543, 2543, 2543, 2543, 2543, 2543, 2543, 2543, 2543, 2543,
       2543, 2543, 2543, 2543, 2543])

## Split

In [10]:
indices = np.arange(df_new.shape[0])
labels = df_new['response'].values

In [11]:
from sklearn.model_selection import train_test_split


indices_train, indices_test, labels_train, labels_test = train_test_split(
    indices, labels, test_size=0.2, random_state=123, shuffle=True, stratify=labels)

indices_train, indices_valid, labels_train, labels_valid = train_test_split(
    indices_train, labels_train, test_size=0.05, random_state=123, shuffle=True, stratify=labels_train)

In [12]:
df_train = df_new.iloc[indices_train]
df_train.to_csv('../data/processed/fireman_example/fireman_example_balanced_train.csv', index=None)

df_valid = df_new.iloc[indices_valid]
df_valid.to_csv('../data/processed/fireman_example/fireman_example_balanced_valid.csv', index=None)

df_test = df_new.iloc[indices_test]
df_test.to_csv('../data/processed/fireman_example/fireman_example_balanced_test.csv', index=None)